version: '3.4'

services:
  # 1. SERVICE USER
  userservice:
    image: userservice-image
    build:
      context: ./UserManagement
      dockerfile: Dockerfile
    ports:
      - "5197:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings__DefaultConnection=Server=sqlserver;Database=UserManagementDb;User Id=sa;Password=Password123!;TrustServerCertificate=True;"
      - "Jwt__Key=1234567890qwertyuiopgsdgsdgsdgsdgsdgsdgsdgdsgsdgsdgsdgdsgsdgsdgdsgsdrewwetwetewtwetewtewtwetwetwetewweewrwererwerwerewrwerwerwerwe"
    depends_on:
      - sqlserver

  # 2. DATABASE
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Password123!
    ports:
      - "1433:1433"

  # 3. API GATEWAY (Đã sửa lỗi)
  gateway:
    build:
      context: ./ApiGateway
      dockerfile: Dockerfile
    ports:
      - "5000:8080"  # Map cổng 8080 của container (.NET 8) ra 5000
    depends_on:
      - userservice
      - sqlserver
      # Đã xóa dòng '- shortenurl-api' đi vì file này chưa có service đó