version: '3.4'

services:
  userservice:
    image: userservice-image
    build:
      context: ./UserManagement
      dockerfile: Dockerfile
    ports:
      - "5197:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings__DefaultConnection=Server=sqlserver;Database=UserManagementDb;User Id=sa;Password=Password123!;TrustServerCertificate=True;"
      - "Jwt__Key=1234567890qwertyuiopgsdgsdgsdgsdgsdgsdgsdgdsgsdgsdgsdgdsgsdgsdgdsgsdrewwetwetewtwetewtewtwetwetwetewweewrwererwerwerewrwerwerwerwe"
    depends_on:
      - sqlserver

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Password123!
    ports:
      - "1433:1433"